services:
  - type: web
    name: tdm-coach-clubs
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn tdm_asistencia.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tdm-coach-clubs-db
          property: connectionString

databases:
  - name: tdm-coach-clubs-db
    plan: free
    databaseName: tdm_coach_clubs
    user: tdm_coach_clubs
