# Generated by Django 6.0.3 on 2026-09-04 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_entrenamiento_detalle_no_entrenamiento_and_more'),
        ('clubs', '0002_perfilusuario_turnoclub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ejercicio',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='entrenamiento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenadores_legacy', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='turno_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrenamientos', to='clubs.turnoclub'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='turno',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Turno 1'), (2, 'Turno 2'), (3, 'Turno 3')], null=True),
        ),
        migrations.AddConstraint(
            model_name='ejercicio',
            constraint=models.UniqueConstraint(fields=('club', 'nombre', 'categoria'), name='ejercicio_unico_por_club_categoria'),
        ),
        migrations.AddConstraint(
            model_name='entrenamiento',
            constraint=models.UniqueConstraint(fields=('club', 'fecha', 'turno_config'), name='entrenamiento_unico_club_fecha_turno_config'),
        ),
    ]
