# Generated by Django 6.0.3 on 2026-09-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_entrenamiento_responsable_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicioturno',
            options={'ordering': ['entrenamiento__fecha', 'entrenamiento__turno_config__orden', 'entrenamiento__turno', 'ejercicio__categoria', 'ejercicio__nombre'], 'verbose_name': 'Ejercicio del turno', 'verbose_name_plural': 'Ejercicios del turno'},
        ),
        migrations.AlterModelOptions(
            name='entrenamiento',
            options={'ordering': ['-fecha', 'turno_config__orden', 'turno']},
        ),
    ]
