# Generated by Django 6.0.3 on 2026-09-04 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_alter_ejercicioturno_options_and_more'),
        ('clubs', '0003_turnoclub_turno_unico_por_club_dia_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('club__isnull', True), ('turno_config__isnull', False), _connector='OR'), name='entrenamiento_comercial_requiere_turno_config'),
        ),
    ]
