# Generated by Django 6.0.3 on 2026-09-04 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0016_limpiar_turno_legacy_comercial'),
        ('clubs', '0003_turnoclub_turno_unico_por_club_dia_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('club__isnull', True), ('turno__isnull', True), _connector='OR'), name='entrenamiento_comercial_sin_turno_legacy'),
        ),
    ]
