# Generated by Django 6.0.3 on 2026-09-08 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0017_entrenamiento_entrenamiento_comercial_sin_turno_legacy'),
        ('clubs', '0003_turnoclub_turno_unico_por_club_dia_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrenamiento',
            constraint=models.CheckConstraint(condition=models.Q(('club__isnull', True), models.Q(('entrenador__isnull', True), ('entrenador_responsable__isnull', True)), _connector='OR'), name='entrenamiento_comercial_sin_entrenador_legacy'),
        ),
    ]
