# Generated by Django 6.0.3 on 2026-10-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0021_ejercicio_comercial_requiere_categoria_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria_config',
            field=models.ForeignKey(blank=True, help_text='Categoría configurable del club.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejercicios', to='asistencia.categoriaejercicio'),
        ),
    ]
