# Generated by Django 6.0.3 on 2026-10-07 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0022_alter_ejercicio_categoria_config'),
        ('clubs', '0005_invitacionclub'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_jugador', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Categoría de jugador',
                'verbose_name_plural': 'Categorías de jugadores',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='asistencia.categoriajugador'),
        ),
        migrations.CreateModel(
            name='PagoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='asistencia.jugador')),
            ],
            options={
                'verbose_name': 'Estado de cuota',
                'verbose_name_plural': 'Estados de cuota',
                'ordering': ['-anio', '-mes', 'jugador__apellido', 'jugador__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriajugador',
            constraint=models.UniqueConstraint(fields=('club', 'nombre'), name='categoria_jugador_unica_por_club'),
        ),
        migrations.AddConstraint(
            model_name='pagojugador',
            constraint=models.UniqueConstraint(fields=('jugador', 'anio', 'mes'), name='pago_jugador_unico_por_mes'),
        ),
    ]
