# Generated by Django 6.0.3 on 2026-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_perfilusuario_turnoclub'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turnoclub',
            constraint=models.UniqueConstraint(fields=('club', 'dia_semana', 'orden'), name='turno_unico_por_club_dia_orden'),
        ),
    ]
