# Generated by Django 6.0.3 on 2026-09-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_turnoclub_turno_unico_por_club_dia_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='estado_pago',
            field=models.CharField(choices=[('al_dia', 'Al día'), ('pendiente', 'Pago pendiente'), ('vencido', 'Vencido')], default='pendiente', help_text='Estado informativo de la suscripción. No bloquea automáticamente el acceso al club.', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='observacion_pago',
            field=models.TextField(blank=True, help_text='Nota interna visible para el administrador técnico.'),
        ),
        migrations.AddField(
            model_name='club',
            name='pagado_hasta',
            field=models.DateField(blank=True, help_text='Última fecha cubierta por el pago del club.', null=True),
        ),
    ]
