# Generated by Django 6.0.3 on 2026-09-17 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_estado_pago_club_observacion_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referencia', models.CharField(blank=True, help_text='Nombre interno opcional para identificar a quién se envió la invitación. Ej: Spin TDM.', max_length=150)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('club_creado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitacion_origen', to='clubs.club')),
            ],
        ),
    ]
